# project in algorithems and optimization

## ${\mathbb{Names:}}$
1- Yuval Kaver, id: 329511125

2- Matan Ginzburg, id: 215717067

## note that we removed some of the graphs since the file was too big to upload to moodle. press run all to see all the graphs

## THE MISHRA’S BIRD FUNCTION WITH CONSTRAINTS

In [2]:
import plotly as pl
import scipy as sp
import plotly.graph_objects as go
import numpy as np
import plotly.express as px
from scipy.optimize import minimize

$f1(x,y) = sin(y)e^{(1-cos(x))^2}+cos(x)e^{(1-sin(y))^2}+(x-y)^2$ <br>
$h1(x,y) = (x+5)^2+(y+5)^2 - 25 < 0$ <br>
$h2(x) = -10 \leq x \leq 0 $ <br>
$h3(y) = -6.5 \leq y \leq 0 $ <br>

we shall normalize the constraints: <br>
$f1(x,y) = sin(y)e^{(1-cos(x))^2}+cos(x)e^{(1-sin(y))^2}+(x-y)^2$ <br>
$h1(x,y) = (x+5)^2+(y+5)^2 - 25 < 0$ <br>
$h2(x) = x \leq 0$ <br>
$h3(x) = -x -10 \leq 0$ <br>
$h4(y) = y \leq 0 $ <br>
$h5(y) = -y -6.5 \leq 0 $ <br>

$D: -10=<x=<0, -7=<y=<0$

In [3]:
def f(x,y):
    return (np.sin(y)*np.exp((1-np.cos(x))**2)+np.cos(x)*np.exp((1-np.sin(y))**2)+(x-y)**2)

def h1(args):
    x = args[0]
    y = args[1]
    return -((x+5)**2 + (y+5)**2 - 25)
def h2(args):
    return -args[0]
def h3(args):
    return -(-args[0]-10)
def h4(args):
    return -args[1]
def h5(args):
    return -(-args[1]-7)

In [ ]:
def graph_3D_func():
    x = np.linspace(-10,0,400)
    y = np.linspace(-7,0,400)
    x, y = np.meshgrid(x, y)
    z = f(x,y)
    fig = go.Figure(data=[go.Surface(z=z, x=x, y=y)])
    fig.update_layout(title='THE MISHRA’S BIRD FUNCTION', autosize=True,width=700, height=500,margin=dict(l=65, r=50, b=65, t=90))
    fig.show()
graph_3D_func()

In [ ]:
def plot_func_as_2D_matrix():
    x = np.linspace(-10,0,400)
    y = np.linspace(-7,0,400)
    x, y = np.meshgrid(x, y)
    z = f(x,y)
    fig = px.imshow(z,x=x,y=x/(10/7),width=800,height=800)
    fig.show()
plot_func_as_2D_matrix()

$\nabla f = \begin{bmatrix}\left(\sin \left(y\right)e^{\left(1-\cos \left(x\right)\right)^2}\cdot \:2\left(1-\cos \left(x\right)\right)\sin \left(x\right)-e^{\left(1-\sin \left(y\right)\right)^2}\sin \left(x\right)+2\left(x-y\right)\right)\\ \left(e^{\left(1-\cos \left(x\right)\right)^2}\cos \left(y\right)-2e^{\left(1-\sin \left(y\right)\right)^2}\cos \left(x\right)\cos \left(y\right)\left(1-\sin \left(y\right)\right)-2\left(x-y\right)\right)\end{bmatrix}$

In [6]:
def gradf(args):
    x = args[0]
    y = args[1]
    return [np.sin(y) * np.exp((1-np.cos(x))**2) * 2*(1-np.cos(x)) * np.sin(x) - np.exp((1-np.sin(y))**2) * np.sin(x) + 2*(x-y),
            np.exp((1-np.cos(x))**2) * np.cos(y) - 2* np.exp((1-np.sin(y))**2) * np.cos(x) * np.cos(y) * (1-np.sin(y)) - 2*(x-y)]


### we wrote the jacobian as a colunm vector so it will fit on the screen
### notice that we orginized the jacobian as follows: 
$\begin{pmatrix}
           f_{xx} \\
           f_{yx} \\
           f_{xy} \\
           f_{yy}
         \end{pmatrix}
$

$D^2 (f) = 
\left(\begin{array}{cc} 2\,{\mathrm{e}}^{{\left(\cos\left(x\right)-1\right)}^2}\,{\sin\left(x\right)}^2\,\sin\left(y\right)-{\mathrm{e}}^{{\left(\sin\left(y\right)-1\right)}^2}\,\cos\left(x\right)+4\,{\mathrm{e}}^{{\left(\cos\left(x\right)-1\right)}^2}\,{\sin\left(x\right)}^2\,\sin\left(y\right)\,{\left(\cos\left(x\right)-1\right)}^2-2\,{\mathrm{e}}^{{\left(\cos\left(x\right)-1\right)}^2}\,\cos\left(x\right)\,\sin\left(y\right)\,\left(\cos\left(x\right)-1\right)+2 \\ -2\,{\mathrm{e}}^{{\left(\cos\left(x\right)-1\right)}^2}\,\cos\left(y\right)\,\sin\left(x\right)\,\left(\cos\left(x\right)-1\right)-2\,{\mathrm{e}}^{{\left(\sin\left(y\right)-1\right)}^2}\,\cos\left(y\right)\,\sin\left(x\right)\,\left(\sin\left(y\right)-1\right)-2\\ -2\,{\mathrm{e}}^{{\left(\cos\left(x\right)-1\right)}^2}\,\cos\left(y\right)\,\sin\left(x\right)\,\left(\cos\left(x\right)-1\right)-2\,{\mathrm{e}}^{{\left(\sin\left(y\right)-1\right)}^2}\,\cos\left(y\right)\,\sin\left(x\right)\,\left(\sin\left(y\right)-1\right)-2 \\ 2\,{\mathrm{e}}^{{\left(\sin\left(y\right)-1\right)}^2}\,\cos\left(x\right)\,{\cos\left(y\right)}^2-{\mathrm{e}}^{{\left(\cos\left(x\right)-1\right)}^2}\,\sin\left(y\right)+4\,{\mathrm{e}}^{{\left(\sin\left(y\right)-1\right)}^2}\,\cos\left(x\right)\,{\cos\left(y\right)}^2\,{\left(\sin\left(y\right)-1\right)}^2-2\,{\mathrm{e}}^{{\left(\sin\left(y\right)-1\right)}^2}\,\cos\left(x\right)\,\sin\left(y\right)\,\left(\sin\left(y\right)-1\right)+2 \end{array}\right)$



In [7]:
def calc_Jacobian(args):
    x = args[0]
    y = args[1]
    return [[2*np.exp((np.cos(x) - 1)**2)*(np.sin(x)**2)*np.sin(y) - np.exp((np.sin(y) - 1)**2)*np.cos(x) + 4*np.exp((np.cos(x) - 1)**2)*(np.sin(x)**2)*np.sin(y)*(np.cos(x) - 1)**2 - 2*np.exp((np.cos(x) - 1)**2)*np.cos(x)*np.sin(y)*(np.cos(x) - 1) + 2, - 2*np.exp((np.cos(x) - 1)**2)*np.cos(y)*np.sin(x)*(np.cos(x) - 1) - 2*np.exp((np.sin(y) - 1)**2)*np.cos(y)*np.sin(x)*(np.sin(y) - 1) - 2],
            [- 2*np.exp((np.cos(x) - 1)**2)*np.cos(y)*np.sin(x)*(np.cos(x) - 1) - 2*np.exp((np.sin(y) - 1)**2)*np.cos(y)*np.sin(x)*(np.sin(y) - 1) - 2, 2*np.exp((np.sin(y) - 1)**2)*np.cos(x)*(np.cos(y)**2) - np.exp((np.cos(x) - 1)**2)*np.sin(y) + 4*np.exp((np.sin(y) - 1)**2)*np.cos(x)*(np.cos(y)**2)*(np.sin(y) - 1)**2 - 2*np.exp((np.sin(y) - 1)**2)*np.cos(x)*np.sin(y)*(np.sin(y) - 1) + 2]]


### minimizing without constraints from $(0,0)$

In [8]:
def f_optimize(args):
    return f(*args)

def minimize_unconstrait_TNC(x0):
    return minimize(f_optimize,x0,method='TNC',jac=gradf)
min = minimize_unconstrait_TNC([0,0])
print("min at:", min.x,"\n f(x,y) = ",min.fun)


min at: [0.90551872 0.66527763] 
 f(x,y) =  1.4870191265420771


### minimization with constraints from (0,0)

In [15]:
def minimize_with_constraits(x0):
    cons = [{'type':'ineq', 'fun': h1},
            {'type':'ineq', 'fun': h2},
            {'type':'ineq', 'fun': h3},
            {'type':'ineq', 'fun': h4},
            {'type':'ineq', 'fun': h5}]
    return minimize(f_optimize,x0=x0,method='trust-constr',jac=gradf,constraints=cons,hess=calc_Jacobian)
min = minimize_with_constraits([0,0] )
print("min at:", min.x,"\n f(x,y) = ",min.fun)

min at: [-3.1302468  -1.58214218] 
 f(x,y) =  -106.76453674926472


### finding global minimum with differential evolution

In [10]:
def find_global_min():
    return sp.optimize.differential_evolution(f_optimize,bounds=[(-10,0),(-7,0)])
min = find_global_min()
print("min at:", min.x,"\n f(x,y) = ",min.fun)

min at: [-3.1302468  -1.58214219] 
 f(x,y) =  -106.76453674926465


In [ ]:
the_point = find_global_min()
ze_point = the_point.x
print(ze_point[0],ze_point[1]) #x and y at the global min... 
#in our case there is only one min globally!


def ploting_and_drawing():
    x = np.linspace(-10,0,400)
    y = np.linspace(-7,0,400)
    x, y = np.meshgrid(x, y)
    z = f(x,y)
    fig = px.imshow(z,x=x,y=x/(10/7),width=800,height=800)

    x_pracent = ze_point[0]/(-10)
    y_pracent = ze_point[1]/(-7)

    our_new_x = 400 - 400*x_pracent
    our_new_y = 400 - 400*y_pracent

    print("our new x and y are:",our_new_x,our_new_y)

    fig.add_shape(type='circle',x0=our_new_x+5, x1=our_new_x-5, y0=our_new_y+5, y1=our_new_y-5,xref='x', yref='y',line_color='cyan') #here the point (x=274,y=309) --> color=-106.7622 is the min.....

    #quick explenation: since we only have one min globally then we will calculate the point compared to its own domain and now for our new domain (400) and thats our point.

    #fig.add_annotation(x=ze_point[0],y=ze_point[1],showarrow=True)
    #fig.add_annotation(x=-3.1302467930983124,y=-1.5821421655644274)
    #fig.update_layout(dragmode='drawrect',newshape=dict(line_color='cyan'))

    fig.show() #
    #config={'modeBarButtonsToAdd':['drawline','drawopenpath','drawclosedpath','drawcircle','drawrect','eraseshape']}


ploting_and_drawing()

## Conjugate Gradient Method

In [12]:
def f_quadratic(x,y,z):
    return  ( x**2 + 2*x*y + 2*x*z + 2*(y**2) + 6*y*z + 6*(z**2) - x + y - 3*z + 1 )  
def grad(x,y,z):
    return np.array([
        2*x + 2*y + 2*z -1,
        2*x + 4*y + 6*z +1,
        2*x + 6*y + 12*z -3
        ])


In [13]:
def conjugate_gradient(x0,iter=2,tol=0.0001): 
    grad_f_k =  A@x0 - b
    d_k = -grad_f_k      #this is our d0

    t_k = -(grad_f_k.T@d_k)/(d_k.T @A @ d_k)  #this is our t0
    next_x = x0 + t_k*d_k                     #calculate x1

    for i in range(iter):
        
        grad_f_k = grad(*next_x)                #this is our grad(xk+1)
        beta_k = (grad_f_k.T @ A @ d_k) / (d_k.T @ A @ d_k)             # this our beta_k
        
        d_k = -grad_f_k + beta_k*d_k                                     #our d_k+1
        t_k = -(grad_f_k.T@d_k)/(d_k.T @A @ d_k)                      # t_k
        if (abs(t_k*d_k)).sum() <= tol:
            print(f"The method converges in {i+1} iterations")
            return next_x
        next_x = next_x + t_k*d_k                                     #calculating x_k+1
    return next_x


#check:
A = 2*np.array([[1,1,1],[1,2,3],[1,3,6]])
b = np.array([1,-1,3]).T
x0 = np.array([0,0,0]).T

min = conjugate_gradient(x0)
print("x = ",min)
print("min_f = ",np.round(f_quadratic(*min),2))

x =  [ 4.5 -7.   3. ]
min_f =  -9.25


## iterative inverse with newton method

In [14]:
def iterative_inverse(A,iter=100,tol=0.0001):
    B = (1/np.trace(A.T @ A))*A.T
    for i in range(iter):
        B = 2*B - B @ A @ B
        if (abs(B - B @ A @ B)).sum() <= tol:
            print(f"the method coverges with the desired tolarence of {tol} in {i} iterations")
            return B
    return B

A =  np.array([[1,1,7,1,1],
               [1,3,1,2,1],
               [2,2,1,9,2],
               [1,0,1,11,9],
               [0,19,0,0,1]])

A_inv = iterative_inverse(A,100,0.00000001)
print("with our method we get:\n",A_inv,"\n\n the actual inverse of A is:\n",np.linalg.inv(A))

the method coverges with the desired tolarence of 1e-08 in 15 iterations
with our method we get:
 [[-0.21239146  1.85449425 -0.27434874 -0.0934053  -0.25275757]
 [ 0.00211218 -0.02065243  0.01267308 -0.00680591  0.05444731]
 [ 0.17343347 -0.25134945  0.0406008  -0.00328561  0.02628491]
 [ 0.03637644 -0.46679183  0.21825862 -0.00610185  0.04881483]
 [-0.04013142  0.39239615 -0.24078855  0.12931237 -0.03449894]] 

 the actual inverse of A is:
 [[-0.21239146  1.85449425 -0.27434874 -0.0934053  -0.25275757]
 [ 0.00211218 -0.02065243  0.01267308 -0.00680591  0.05444731]
 [ 0.17343347 -0.25134945  0.0406008  -0.00328561  0.02628491]
 [ 0.03637644 -0.46679183  0.21825862 -0.00610185  0.04881483]
 [-0.04013142  0.39239615 -0.24078855  0.12931237 -0.03449894]]
