# ${\color{pink}{Homework-Assignment4}}$

### Homework Assignment #4

#### Question 1: Convolution Theorem

**a. Convolution in Fourier Space**: Prove that the Fourier transform of the convolution of two functions $f$ and $g$, denoted as $\mathcal{F}(f \star g)$, equals the pointwise product of their Fourier transforms:  
$$
\mathcal{F}(f \star g) = \mathcal{F}(f) \cdot \mathcal{F}(g).
$$  
Specify whether your proof is for continuous functions or discrete signals and clearly state any assumptions made.

---

#### Question 2: Properties of Convolution

**a. Commutativity**: Prove that the convolution operation is commutative:  
$$
f \star g = g \star f.
$$

**b. Distributivity**: Prove the distributive property of convolution:  
$$
f \star (\alpha g + \beta h) = \alpha (f \star g) + \beta (f \star h),
$$  
where $ \alpha, \beta \in \mathbb{R} $.

**c. Shift Equivariance**: Prove that convolution is shift-invariant:  
$$
f(x) \star g(x - d) = (f \star g)(x - d).
$$

**d. Scaling Property**: Prove that if a function $ f(x) $ is scaled in its argument by a factor $ a > 0 $, then its convolution with a function $ g(x) $ satisfies:  
$$
f(ax) \star g(ax) = \frac{1}{a} \big(f \star g\big)(ax).
$$
Clearly state any assumptions and steps in your proof.

---

#### Question 3: Derivative and Inverse of Convolution

**a. Derivative of Convolution**: Derive the expression for the derivative of the convolution $ f(x) \star g(x) $:  
$$
\frac{d}{dx} \big(f(x) \star g(x)\big).
$$  
Verify this property for specific functions of your choice, such as $ f(x) = e^{-x^2} $ and $ g(x) = \sin(x) $.

**b. Inverse of Convolution**: Discuss the conditions under which the convolution $ f(x) \star g(x) $ can be inverted. Derive the theoretical framework for deconvolution or solving for $ f(x) $ or $ g(x) $ given their convolution.

---

#### Question 4 (Optional, Coding): Practical Verification of Convolution Properties

**a. Implementation**: Implement the convolution operation using Python (e.g., PyTorch or NumPy) and verify the properties discussed in Question 2 for specific example functions $ f(x) $ and $ g(x) $.  

**b. Fourier Transform Connection**: Use the Fourier transform to verify the convolution theorem numerically. Show that $ \mathcal{F}(f \star g) = \mathcal{F}(f) \cdot \mathcal{F}(g) $ for your chosen functions $ f(x) $ and $ g(x) $.

**c. Applications**: Briefly explain how these properties are utilized in convolutional neural networks (CNNs).

# ${\color{pink}{---------------------------}}$

# ${\color{pink}{Conovolution- Theorem!}}$

$$
\mathcal{F}(f \star g) = \mathcal{F}(f) \cdot \mathcal{F}(g).
$$  

$$
\mathcal{F}(f \star g)(u) = \int_{-\infty}^{\infty}\ (f \star g)(t) \cdot e^{-2\pi iut} dt = \int_{-\infty}^{\infty}\ [ \int_{-\infty}^{\infty}\ f(s) \cdot g(t-s)  ds ] e^{-2\pi iut} dt 
=\int_{-\infty}^{\infty}\ f(s) [\int_{-\infty}^{\infty}\  g(t-s) \cdot e^{-2\pi iut} dt ]ds =
$$

$$
|||\tilde{t} = t-s ||| t = \tilde{t}+s ||| d\tilde{t} = dt|||
$$

$$
= \int_{-\infty}^{\infty}\ f(s) [\int_{-\infty}^{\infty}\ g(\tilde{t}) \cdot e^{-2\pi iu(\tilde{t}+s)} d\tilde{t} ] ds =
\int_{-\infty}^{\infty}\ f(s) \cdot e^{-2\pi ius} \int_{-\infty}^{\infty}\ g(\tilde{t}) \cdot e^{-2\pi iu\tilde{t}} d\tilde{t} ] ds = 
\int_{-\infty}^{\infty}\ f(s) \cdot e^{-2\pi ius} ds \cdot \mathcal{F}(g) = \mathcal{F}(f) \cdot \mathcal{F}(g).
$$


assumptions:

-f,g continuous func that have Fourier transforms...

# ${\color{pink}{Commutativity}}$

$$
f \star g = g \star f
$$

$$
f \star g = \int_{-\infty}^{\infty}\ f(s) \cdot g(t-s) ds = 
$$

$$
||| \tilde{s} = t-s ||| s = t - \tilde{s} ||| d\tilde{s} = -ds|||
$$

$$
= - \int_{\infty}^{-\infty}\ f(t - \tilde{s}) \cdot g(\tilde{s}) d\tilde{s} = \int_{-\infty}^{\infty}\ g(\tilde{s}) \cdot f(t - \tilde{s}) d\tilde{s} = g \star f
$$

# ${\color{pink}{Distributivity}}$

$$
f \star (\alpha g + \beta h) = \alpha (f \star g) + \beta (f \star h),
$$  
where $ \alpha, \beta \in \mathbb{R} $.

$$
f \star (\alpha g + \beta h) = \int_{-\infty}^{\infty}\ f(s) \cdot (\alpha g + \beta h)(t-s) ds = \int_{-\infty}^{\infty}\ f(s) \cdot (\alpha g(t-s) + \beta h(t-s)) ds=
$$

$$
\int_{-\infty}^{\infty}\ [f(s) \cdot \alpha g(t-s) + f(s) \cdot \beta h(t-s)] ds = \int_{-\infty}^{\infty}\ [\alpha \cdot f(s) \cdot  g(t-s) + \beta  \cdot f(s) \cdot h(t-s)] ds=
$$

$$
\int_{-\infty}^{\infty}\ \alpha \cdot f(s) \cdot  g(t-s) ds + \int_{-\infty}^{\infty}\ \beta  \cdot f(s) \cdot h(t-s)ds = 
$$

$$
\alpha \int_{-\infty}^{\infty}\ f(s) \cdot  g(t-s) ds + \beta \int_{-\infty}^{\infty}\ f(s) \cdot h(t-s)ds = \alpha (f \star g) + \beta (f \star h)
$$


# ${\color{pink}{Shift -Equivariance}}$ 

$$
f(t) \star g(t - d) = (f \star g)(t - d).
$$

$$
f(t) \star g(t - d) = \int_{-\infty}^{\infty}\ f(s) \cdot g(t-d-s) ds = \int_{-\infty}^{\infty}\ f(s) \cdot g((t-s )-d) ds =
 \int_{-\infty}^{\infty}\ f(s) \cdot g(q-s) ds = (f \star g)(q) = (f \star g)(t - d)
$$
$$
|||q = t-d|||
$$


# ${\color{pink}{Scaling-Property}}$

 $$
f(at) \star g(at) = \frac{1}{a} \big(f \star g\big)(at).
$$


$$
||| f(at) = q(t) , g(at) = y(t)||| = 
$$

$$
f(at) \star g(at) = q(t) \star y(t) = \int_{-\infty}^{\infty}\ q(s) \cdot y(t-s) ds = 
$$

$$
\int_{-\infty}^{\infty}\ f(as) \cdot g(a(t-s)) ds = 
$$

$$
|||as = w ||| s = \frac{w}{a} ||| ds = \frac{1}{a} dw|||
$$

$$
\int_{-\infty}^{\infty}\ f(w) \cdot g(a(t-\frac{w}{a})) \frac{1}{a} dw = \frac{1}{a} \int_{-\infty}^{\infty}\ f(w) \cdot g(at-w)  dw = \frac{1}{a} \big(f \star g\big)(at)
$$

# ${\color{pink}{Derivative-of-Convolution}}$

$$
\frac{d}{dt} \big(f(t) \star g(t)\big) = \frac{d}{dt} \int_{-\infty}^{\infty}\ f(s) \cdot g(t-s) ds = \int_{-\infty}^{\infty}\ \frac{d}{dt} f(s) \cdot g(t-s) ds =
\int_{-\infty}^{\infty}\ f(s) \cdot \frac{d}{dt} g(t-s) ds =
$$

$$
\int_{-\infty}^{\infty}\ f(s) \cdot g'(t-s) ds = \big(f(t) \star g'(t)\big) = \big(f(t) \star g(t)\frac{d}{dt}\big)
$$  
same for g*f:
$$
\frac{d}{dt} \big(f(t) \star g(t)\big) = \frac{d}{dt} \big(g(t) \star f(t)\big) = \big(g(t) \star f(t)\frac{d}{dt}\big)
$$

Verify this property for specific functions of your choice, such as $ f(t) = e^{-t^2} $ and $ g(t) = \sin(t) $.

$$\big(f(t) \star g'(t)\big) = e^{-t^2} \star (\sin(t))' = e^{-t^2} \star \cos(t) = \int_{-\infty}^{\infty}\ e^{-s^2} \cdot \cos(t-s) ds $$
$$ \frac{d}{dt} \big(f(t) \star g(t)\big) = \frac{d}{dt} \int_{-\infty}^{\infty}\ e^{-s^2} \cdot \sin(t-s) ds = \int_{-\infty}^{\infty}\ e^{-s^2} \cdot \frac{d}{dt}\sin(t-s) ds =
\int_{-\infty}^{\infty}\ e^{-s^2} \cdot \cos(t-s) ds  $$ 

and because of Commutativity the opposite is the same

# ${\color{pink}{Inverse-of-Convolution}}$

$$
\mathcal{F}(h) =  \mathcal{F}(f) \cdot \mathcal{F}(g) = \mathcal{F}(f\star g) 
$$

$$
\mathcal{F}(f) = \frac{\mathcal{F}(f\star g)}{\mathcal{F}(g)} ==> f = \mathcal{F}^{-1}(f) = \mathcal{F}^{-1}(\frac{\mathcal{F}(f\star g)}{\mathcal{F}(g)})
$$

the conditions:

~ $\mathcal{F}(g)$ and $\mathcal{F}(f)$ and $\mathcal{F}(f \star g)$ != 0

~ both g and f gotta have Fourier transform

in order for the conovulotion to be inverted we need both $f(t)$ and $g(t)$ to have Fuoierer transform by their own, 
$$ \int_{-\infty}^{\infty}\ |f(t)| < \infty ,\textnormal(or),  \int_{-\infty}^{\infty}\ |f(t)|^2 < \infty $$ 
$$ \int_{-\infty}^{\infty}\ |g(t)| < \infty ,\textnormal(or), \int_{-\infty}^{\infty}\ |g(t)|^2 < \infty $$


# ${\color{pink}{Coding!}}$

#### ~ unfortunately not all :( ~

In [1]:
import numpy as np
import scipy
from scipy import signal

np.set_printoptions(suppress=True,precision=5) #so numbers will be pretty

In [8]:
#$ f(t) = e^{-t^2} $ and $ g(t) = \sin(t) $
def func_f(t):
    return np.exp(-t**2)
def func_g(t):
    return np.sin(t)
def func_h(t):
    return np.cos(t)
t = np.array(range(0,5))/10

In [18]:
#fourier transform check(doesn't work unfortunately):

f_transform = abs(np.fft.fft(func_f(t)))
g_transform = abs(np.fft.fft(func_g(t)))
furier = abs(f_transform * g_transform)

#convo = abs( scipy.signal.convolve(func_f(t) , func_g(t),mode="same") )
convolution_f_g = abs ( np.convolve(func_f(t), func_g(t), mode='same'))
convo_transform = abs(np.fft.fft(convolution_f_g))



print("-----Regular multy-----")
print(furier)
print("-----With CONOVOLUTION-----")
print(convolution_f_g)        #*furier[0]/convo_transform[0]
print("---Shapes?---")
print(np.shape(furier),np.shape(convo_transform))
print("--DIFF--\n",furier - convo_transform)




-----Regular multy-----
[4.63881 0.06939 0.02455 0.02455 0.06939]
-----With CONOVOLUTION-----
[0.29751 0.58813 0.96412 0.93612 0.81353]
---Shapes?---
(5,) (5,)
--DIFF--
 [ 1.0394  -0.76121 -0.27116 -0.27116 -0.76121]


In [5]:
#checking some properties:

print("f*g = g*f:")
fg_con = scipy.signal.convolve(func_f(t),func_g(t))
gf_con = scipy.signal.convolve(func_g(t),func_f(t))
print(fg_con,"\n",gf_con)
print("-----")
a,b = 3,5
print("f*(ag+bh) = a(f*g)+b(f*h):")
f_all_con = scipy.signal.convolve(func_f(t),a*func_g(t)+b*func_h(t))
f_g_con = a*scipy.signal.convolve(func_f(t),func_g(t)) 
f_h_con = b*scipy.signal.convolve(func_f(t),func_h(t))
print(f_all_con,"\n",f_g_con + f_h_con)
print("----")
#I dont know how to do shift and scaling


f*g = g*f:
[0.      0.09983 0.29751 0.58813 0.5747  0.4655  0.27009] 
 [0.      0.09983 0.29751 0.58813 0.5747  0.4655  0.27009]
-----
f*(ag+bh) = a(f*g)+b(f*h):
[ 5.      10.22477 15.52233 20.74225 15.70827 10.46446  5.17581] 
 [ 5.      10.22477 15.52233 20.74225 15.70827 10.46446  5.17581]
----


# ${\color{pink}{Bonus}}$

~I didn't want to delete after writing...~

$$ \textcolor{purple}{\mathcal{F}^{-1}(f)(t) = \mathcal{F}(f)(-t)}$$


$$
\textcolor{yellow}{\mathcal{F}^{-1}(f \star g) =   \int_{-\infty}^{\infty}\ \mathcal{F}(f \star g)(u) \cdot e^{+2\pi iut} dt = \int_{-\infty}^{\infty}\ [ \mathcal{F}(f) \cdot \mathcal{F}(g)] e^{+2\pi iut} dt}
$$

$$
\textcolor{cyan}{= \int_{-\infty}^{\infty}\ [ \int_{-\infty}^{\infty}\ f(s) \cdot g(t-s) ds ] e^{+2\pi iut} dt = 
\int_{-\infty}^{\infty}\ f(s) [\int_{-\infty}^{\infty}\ g(t-s)  e^{+2\pi iut}dt ] ds}
$$

$$
\textcolor{lime}{|||\tilde{t} = t-s ||| t = \tilde{t}+s ||| d\tilde{t} = dt|||}
$$

$$
\textcolor{lavender}{= \int_{-\infty}^{\infty}\ f(s) [\int_{-\infty}^{\infty}\ g(\tilde{t}) \cdot e^{+2\pi iu(\tilde{t}+s)} d\tilde{t} ] ds =
\int_{-\infty}^{\infty}\ f(s) \cdot e^{+2\pi ius} \int_{-\infty}^{\infty}\ g(\tilde{t}) \cdot e^{+2\pi iu\tilde{t}} d\tilde{t} ] ds = 
\int_{-\infty}^{\infty}\ f(s) \cdot e^{+2\pi ius} ds \cdot \mathcal{F}^{-1}(g) = \mathcal{F}^{-1}(f) \cdot \mathcal{F}^{-1}(g).}
$$
